"""定义稀疏向量索引阶段使用的常量。"""

DEFAULT_SPARSE_VECTOR_MODEL_NAME = "BAAI/bge-m3"
DEFAULT_SPARSE_VECTOR_PROVIDER = "bge_m3"
DEFAULT_SPARSE_VECTOR_NAME = "sparse_text"

SPARSE_VECTOR_STATUS_PENDING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXED = "SUCCESS"
SPARSE_VECTOR_STATUS_SUCCESS = "SUCCESS"
SPARSE_VECTOR_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_DELETING = "PENDING"
SPARSE_VECTOR_STATUS_DELETED = "SUCCESS"
SPARSE_VECTOR_STATUS_DELETE_FAILED = "FAILED"

SPARSE_VECTOR_STATUSES = {
    SPARSE_VECTOR_STATUS_PENDING,
    SPARSE_VECTOR_STATUS_SUCCESS,
    SPARSE_VECTOR_STATUS_FAILED,
}
