"""定义稀疏向量索引阶段使用的常量。"""

DEFAULT_SPARSE_VECTOR_MODEL_NAME = "BAAI/bge-m3"
DEFAULT_SPARSE_VECTOR_PROVIDER = "bge_m3"
DEFAULT_SPARSE_VECTOR_NAME = "sparse_text"

# Provider 取值：
# - ``bge_m3``      ：本地进程内加载 BGE-M3 模型推理（默认，零外部依赖）。
# - ``bge_m3_http`` ：调用远程 bge-m3-server 的 /encode HTTP 接口推理。
SPARSE_VECTOR_PROVIDER_LOCAL = "bge_m3"
SPARSE_VECTOR_PROVIDER_HTTP = "bge_m3_http"

SPARSE_VECTOR_STATUS_PENDING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXED = "SUCCESS"
SPARSE_VECTOR_STATUS_SUCCESS = "SUCCESS"
SPARSE_VECTOR_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_DELETING = "PENDING"
SPARSE_VECTOR_STATUS_DELETED = "SUCCESS"
SPARSE_VECTOR_STATUS_DELETE_FAILED = "FAILED"

SPARSE_VECTOR_STATUSES = {
    SPARSE_VECTOR_STATUS_PENDING,
    SPARSE_VECTOR_STATUS_SUCCESS,
    SPARSE_VECTOR_STATUS_FAILED,
}
