"""文件解析流水线状态常量。"""

PIPELINE_STATUS_PENDING = "PENDING"
PIPELINE_STATUS_PROCESSING = "PROCESSING"
PIPELINE_STATUS_SUCCESS = "SUCCESS"
PIPELINE_STATUS_FAILED = "FAILED"

STAGE_STATUS_PENDING = "PENDING"
# PROCESSING 三态扩展：与 PIPELINE_STATUS_PROCESSING 对齐，覆盖单阶段进行中。
STAGE_STATUS_PROCESSING = "PROCESSING"
STAGE_STATUS_SUCCESS = "SUCCESS"
STAGE_STATUS_FAILED = "FAILED"

# 文档清洗：先前的"解析+上传 markdown"语义下沉到本阶段。
# brief / acceptance 中使用术语 PARSING；代码侧保持 CLEANING（migration 0007 已落地）。
POST_PROCESS_STAGE_CLEANING = "CLEANING"
POST_PROCESS_STAGE_CHUNKING = "CHUNKING"
POST_PROCESS_STAGE_VECTORIZING = "VECTORIZING"
# 预分词为一等独立阶段，排在 VECTORIZING 与 ES_INDEXING 之间。
POST_PROCESS_STAGE_PRETOKENIZE = "PRETOKENIZE"
POST_PROCESS_STAGE_ES_INDEXING = "ES_INDEXING"
# 稀疏向量阶段：解析主流水线的最后一段，与 dense 阶段对称。
POST_PROCESS_STAGE_SPARSE_VECTORIZING = "SPARSE_VECTORIZING"
# 重试前置校验失败专用的 failed_stage 取值；不属于 recover_from_stage 序列。
POST_PROCESS_STAGE_RETRY_VALIDATION = "RETRY_VALIDATION"

# 6 阶段执行顺序：用于编排层统一循环、跳过、推断 recover_from_stage。
# RETRY_VALIDATION 不进入此序列（仅用作 failed_stage 终态标识）。
POST_PROCESS_STAGE_ORDER = (
    POST_PROCESS_STAGE_CLEANING,
    POST_PROCESS_STAGE_CHUNKING,
    POST_PROCESS_STAGE_VECTORIZING,
    POST_PROCESS_STAGE_PRETOKENIZE,
    POST_PROCESS_STAGE_ES_INDEXING,
    POST_PROCESS_STAGE_SPARSE_VECTORIZING,
)

MAX_FAILURE_REASON_LENGTH = 512
