"""文件级解析后处理 pipeline 状态常量。"""

PIPELINE_STATUS_PENDING = "PENDING"
PIPELINE_STATUS_PROCESSING = "PROCESSING"
PIPELINE_STATUS_SUCCESS = "SUCCESS"
PIPELINE_STATUS_FAILED = "FAILED"

STAGE_STATUS_PENDING = "PENDING"
STAGE_STATUS_SUCCESS = "SUCCESS"
STAGE_STATUS_FAILED = "FAILED"

POST_PROCESS_STAGE_CHUNKING = "CHUNKING"
POST_PROCESS_STAGE_VECTORIZING = "VECTORIZING"
# 预分词为一等独立阶段，排在 VECTORIZING 与 ES_INDEXING 之间。
POST_PROCESS_STAGE_PRETOKENIZE = "PRETOKENIZE"
POST_PROCESS_STAGE_ES_INDEXING = "ES_INDEXING"

MAX_FAILURE_REASON_LENGTH = 512
