"""文件解析流水线状态常量。"""

PIPELINE_STATUS_PENDING = "PENDING"
PIPELINE_STATUS_PROCESSING = "PROCESSING"
PIPELINE_STATUS_SUCCESS = "SUCCESS"
PIPELINE_STATUS_FAILED = "FAILED"

STAGE_STATUS_PENDING = "PENDING"
STAGE_STATUS_SUCCESS = "SUCCESS"
STAGE_STATUS_FAILED = "FAILED"

# 文档清洗：先前的"解析+上传 markdown"语义下沉到本阶段。
POST_PROCESS_STAGE_CLEANING = "CLEANING"
POST_PROCESS_STAGE_CHUNKING = "CHUNKING"
POST_PROCESS_STAGE_VECTORIZING = "VECTORIZING"
# 预分词为一等独立阶段，排在 VECTORIZING 与 ES_INDEXING 之间。
POST_PROCESS_STAGE_PRETOKENIZE = "PRETOKENIZE"
POST_PROCESS_STAGE_ES_INDEXING = "ES_INDEXING"

MAX_FAILURE_REASON_LENGTH = 512
