"""定义稀疏向量索引阶段使用的常量。"""

# Qdrant named sparse vector 的字段名；写入与召回共用，per-user 解析路径同样依赖。
DEFAULT_SPARSE_VECTOR_NAME = "sparse_text"

SPARSE_VECTOR_STATUS_PENDING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXED = "SUCCESS"
SPARSE_VECTOR_STATUS_SUCCESS = "SUCCESS"
SPARSE_VECTOR_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_DELETING = "PENDING"
SPARSE_VECTOR_STATUS_DELETED = "SUCCESS"
SPARSE_VECTOR_STATUS_DELETE_FAILED = "FAILED"

SPARSE_VECTOR_STATUSES = {
    SPARSE_VECTOR_STATUS_PENDING,
    SPARSE_VECTOR_STATUS_SUCCESS,
    SPARSE_VECTOR_STATUS_FAILED,
}
