"""定义向量存储模块使用的状态、默认配置与字段常量。"""

CHUNK_STATUS_PENDING = "PENDING"
CHUNK_STATUS_INDEXING = "INDEXING"
CHUNK_STATUS_INDEXED = "INDEXED"
CHUNK_STATUS_FAILED = "FAILED"
CHUNK_STATUS_DELETING = "DELETING"
CHUNK_STATUS_DELETED = "DELETED"
CHUNK_STATUS_DELETE_FAILED = "DELETE_FAILED"

CHUNK_ACTIVE_STATUSES = (
    CHUNK_STATUS_PENDING,
    CHUNK_STATUS_INDEXING,
    CHUNK_STATUS_INDEXED,
    CHUNK_STATUS_FAILED,
)

CHUNK_UPDATE_ALLOWED_STATUSES = (
    CHUNK_STATUS_INDEXED,
    CHUNK_STATUS_FAILED,
)

CHUNK_DELETE_ALLOWED_STATUSES = (
    CHUNK_STATUS_INDEXED,
    CHUNK_STATUS_INDEXING,
    CHUNK_STATUS_FAILED,
)

CHUNK_DELETE_PROTECTED_STATUSES = (
    CHUNK_STATUS_DELETING,
    CHUNK_STATUS_DELETED,
    CHUNK_STATUS_DELETE_FAILED,
)

CHUNK_DELETE_RETRY_STATUSES = (
    CHUNK_STATUS_DELETING,
    CHUNK_STATUS_DELETE_FAILED,
)

DEFAULT_BUCKET_COUNT = 128
DEFAULT_COLLECTION_PREFIX = "kb_bucket"
DEFAULT_RETRY_LIMIT = 3
DEFAULT_RETRY_INTERVAL_SECONDS = 300
DEFAULT_INDEXING_STALE_SECONDS = 900
DEFAULT_QDRANT_TIMEOUT_SECONDS = 5

QDRANT_PAYLOAD_INDEX_FIELDS = ("user_id", "set_id", "doc_id")
MAX_ERROR_MSG_LENGTH = 512
