CHUNK_LIFECYCLE_ACTIVE = "ACTIVE"
CHUNK_LIFECYCLE_DELETING = "DELETING"
CHUNK_LIFECYCLE_DELETED = "DELETED"
CHUNK_LIFECYCLE_DELETE_FAILED = "DELETE_FAILED"
CHUNK_LIFECYCLE_DELETE_PROTECTED_STATUSES = (
    CHUNK_LIFECYCLE_DELETING,
    CHUNK_LIFECYCLE_DELETED,
    CHUNK_LIFECYCLE_DELETE_FAILED,
)
CHUNK_LIFECYCLE_DELETE_RETRY_STATUSES = (
    CHUNK_LIFECYCLE_DELETING,
    CHUNK_LIFECYCLE_DELETE_FAILED,
)

CHUNK_STATUS_PENDING = "PENDING"
CHUNK_STATUS_INDEXING = "PENDING"
CHUNK_STATUS_INDEXED = "SUCCESS"
CHUNK_STATUS_SUCCESS = "SUCCESS"
CHUNK_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_PENDING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXED = "SUCCESS"
SPARSE_VECTOR_STATUS_SUCCESS = "SUCCESS"
SPARSE_VECTOR_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_DELETING = "PENDING"
SPARSE_VECTOR_STATUS_DELETED = "SUCCESS"
SPARSE_VECTOR_STATUS_DELETE_FAILED = "FAILED"
ES_STATUS_PENDING = "PENDING"
ES_STATUS_SUCCESS = "SUCCESS"
ES_STATUS_FAILED = "FAILED"

CHUNK_UPDATE_ALLOWED_STATUSES = (CHUNK_STATUS_INDEXED, CHUNK_STATUS_FAILED)
CHUNK_DELETE_ALLOWED_STATUSES = (CHUNK_STATUS_PENDING, CHUNK_STATUS_SUCCESS, CHUNK_STATUS_FAILED)
