CHUNK_STATUS_PENDING = "PENDING"
CHUNK_STATUS_INDEXING = "INDEXING"
CHUNK_STATUS_DELETING = "DELETING"
CHUNK_STATUS_DELETED = "DELETED"
CHUNK_STATUS_DELETE_FAILED = "DELETE_FAILED"
CHUNK_STATUS_INDEXED = "INDEXED"
CHUNK_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_PENDING = "PENDING"
SPARSE_VECTOR_STATUS_INDEXING = "INDEXING"
SPARSE_VECTOR_STATUS_INDEXED = "INDEXED"
SPARSE_VECTOR_STATUS_FAILED = "FAILED"
SPARSE_VECTOR_STATUS_DELETING = "DELETING"
SPARSE_VECTOR_STATUS_DELETED = "DELETED"
SPARSE_VECTOR_STATUS_DELETE_FAILED = "DELETE_FAILED"
ES_STATUS_PENDING = "PENDING"
ES_STATUS_SUCCESS = "SUCCESS"
ES_STATUS_FAILED = "FAILED"
CHUNK_DELETE_PROTECTED_STATUSES = (
    CHUNK_STATUS_DELETING,
    CHUNK_STATUS_DELETED,
    CHUNK_STATUS_DELETE_FAILED,
)
CHUNK_UPDATE_ALLOWED_STATUSES = (CHUNK_STATUS_INDEXED, CHUNK_STATUS_FAILED)
CHUNK_DELETE_ALLOWED_STATUSES = (
    CHUNK_STATUS_INDEXED,
    CHUNK_STATUS_INDEXING,
    CHUNK_STATUS_FAILED,
)
CHUNK_DELETE_RETRY_STATUSES = (CHUNK_STATUS_DELETING, CHUNK_STATUS_DELETE_FAILED)
